services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONF: ${FRONT_BUILD_CONF:-development}
    container_name: frontend-container
    ports:
      - "4200:80"
    restart: unless-stopped
    networks:
      - igss-network

networks:
  igss-network:
    external: true

