services:
  frontend:
    build: 
    context: .
    dockerfile: Dockerfile
    args:
      BUILD_CONF: ${FRONT_BUILD_CONF:-development}  # 👈 default a development    
    container_name: frontend-container
    ports:
      - "4200:80"            # Host:Container
    restart: unless-stopped
    networks:
      - igss-network

networks:
  igss-network:
    external: true